language: python
python:
- 3.8
env:
  PYPI_TOKEN:
    secure: eGWMffVkIMEljlLjUu9ONcdJcf5gQtx31hNy35hz4iExh3msdfuYUyAd5TN/Di/T87Uw5KlD14DG3TCDxsKECJVSk/WUMoqdTj3jUfprbZS9SFyuFYYDooZOIJ6cnXtncSs6g9CtYklsT0EDvgm4V1nt2K4i5uk8KduJDXtjQZROjjkyFKTX35tcvwISIh93yR224tH9NmhYOBHaQhkwo4hfmsgtbxnTltl/TadB3DI1D8qlbc0cG/im8H6E16U/71bKzAan8oQJvoFBAuALv/oYWrmVaDbI3SR3EeXGI+b/6C05J9ewRKS5C/OP6JGxcNy0mQ8H2z/7lnNM10V309JFRDl/fCO0D3YNQPlJbR542eOVLN0nmgaByy6QAgpjcRvy9DB1OrdoO+i7dHd+msHMERnO1XXsttOahpjYzp3gzfqFuwMmwN39kffWGtdlj7wWwi9pqYp5TXTpGA4Qp9sHuSP8Rat0wqCaU1qg80E8FQqJcbSX3OEkMM88mbZjmVNJDqnj3dgLZ7S/GkQdIgEBDjPOYva88Y1mD0lilxE9NRjP7HuxJkoKyNgU2Ojy0Yi5xno3ODcxz1TprgnNCHL7IdvvdQN5EEoWdJMmZY05BbDsMdmK6S3e8Yh8ly51LAUyCgINYxCnBTfAw2TNrh0qTVXKb3cqOsCdcHCOtac=

script:
- pip install twine pytest
- pip install -e .
- pytest -s
- python setup.py sdist bdist_wheel
- twine check dist/*
- if [ "$TRAVIS_BRANCH" = "main" ]; then twine upload --skip-existing dist/* -u __token__
  -p $PYPI_TOKEN; fi
